export const ActionTypes={
    FETCH_PRODUCTS :"FETCH_PRODUCTS",
    FETCH_PRODUCT:"FETCH_PRODUCT",
    SET_PRODUCTS :"SET_PRODUCTS",
    SELECTED_PRODUCTS:"SELECTED_PRODUCTS",
    CART_PRODUCT:"CART_PRODUCT",
    REMOVE_PRODUCT:"REMOVE_PRODUCT"
}